<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LLLGMOJ" failures="4" tests="14" name="RetryMulitple" time="0.223" errors="0" timestamp="2024-06-06T08:51:20 IST">
  <testcase classname="day9.runTimeRetryfailedTc.Test001" name="Test1" time="0.042">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test001" name="Test1" time="0.004">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test001" name="Test1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at day9.runTimeRetryfailedTc.Test001.Test1(Test001.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test001" name="Test2" time="0.007">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test001" name="Test2" time="0.006">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test001" name="Test2" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at day9.runTimeRetryfailedTc.Test001.Test2(Test001.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test002" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test002" name="Test1" time="0.003">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test002" name="Test1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at day9.runTimeRetryfailedTc.Test002.Test1(Test002.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test002" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test002" name="Test2" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test002" name="Test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at day9.runTimeRetryfailedTc.Test002.Test2(Test002.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test002" name="Test3" time="0.002">
    <skipped/>
  </testcase> <!-- Test3 -->
  <testcase classname="day9.runTimeRetryfailedTc.Test002" name="Test3" time="0.002"/>
</testsuite> <!-- RetryMulitple -->
